package com.haomostudio.milk.dao;

import com.haomostudio.milk.po.AboutUs;
import com.haomostudio.milk.po.AboutUsExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AboutUsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    long countByExample(AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    int deleteByExample(AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    int insert(AboutUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    int insertSelective(AboutUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    List<AboutUs> selectByExampleWithRowbounds(AboutUsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    List<AboutUs> selectByExample(AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    AboutUs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") AboutUs record, @Param("example") AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    int updateByExample(@Param("record") AboutUs record, @Param("example") AboutUsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    int updateByPrimaryKeySelective(AboutUs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table about_us
     *
     * @mbg.generated Sun Jul 15 16:09:42 CST 2018
     */
    int updateByPrimaryKey(AboutUs record);
}